services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '4000:80'
  node:
    build:
      dockerfile: Dockerfile.dev
      context: ./node
    volumes:
      - /app/node_modules
      - ./node:/app