services:
  nginx:
    restart: always
    image: nginx
    depends_on:
      - node
      - client
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '4000:80'
  node:
    build:
      dockerfile: Dockerfile.dev
      context: ./node
    volumes:
      - /app/node_modules
      - ./node:/app
    depends_on:
      - redis
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  redis:
    image: redis:8.0-rc1